### PR TITLE
Implemented manual search function for unknown commands

### PR DESCRIPTION
**Pull request by dixxe**
Small function that can help creating command files or find explanation of unknown commands. This is my first ever attempt to contribute! I hope it's fine ^^'

### CODE REVIEW

**Comment by dixxe** [comment]
By manual I mean it queries "man" command. Sorry for misunderstanding

**Comment by juanmilkah** [comment]
Honestly I didn't wanna implement that feature, reason being their already
exist the "man" linux command.
I fell like I wouldn't fully implement it, so I assumed the end user would
just [man <command>] incase they wanna get more info about a command

**Comment by juanmilkah** [comment]
> Small function that can help creating command files or find explanation of unknown commands. This is my first ever attempt to contribute! I hope it's fine ^^'

I think the easier option is to edit the linux file, and add more commands. The goal is to have all available linux commands in the file with a simple description of the command.

**Comment by dixxe** [comment]
Okay, no problem! I understand your point 😊
Anyways that was fun working with your code! Have a nice day!

**Comment by juanmilkah** [comment]
Thank you, you too!

**Comment by williammuchui** [comment]
Not necessary as linux file has almost all available commands at this time. Any missing commands can be added directly into the linux file

**Pull request closed without merging**
